name: marimo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anyio=4.10.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - click=8.2.1
  - docutils=0.22
  - exceptiongroup=1.3.0
  - h11=0.16.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - loro=1.5.4
  - marimo=0.15.0
  - markdown=3.8.2
  - narwhals=2.1.2
  - ncurses=6.5
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.4
  - pip=25.2
  - psutil=7.0.0
  - pygments=2.19.2
  - pymdown-extensions=10.16.1
  - python=3.13.5
  - python_abi=3.13
  - pyyaml=6.0.2
  - readline=8.2
  - ruff=0.12.10
  - sniffio=1.3.1
  - starlette=0.47.2
  - tk=8.6.13
  - tomlkit=0.13.3
  - typing_extensions=4.14.1
  - tzdata=2025b
  - uvicorn=0.35.0
  - websockets=15.0.1
  - yaml=0.2.5
  - zipp=3.23.0
  - pip:
      - altair==5.5.0
      - attrs==25.3.0
      - gcloud==0.18.3
      - googleapis-common-protos==1.70.0
      - httplib2==0.22.0
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - markupsafe==3.0.2
      - numpy==2.3.2
      - oauth2client==4.1.3
      - polars==1.32.3
      - protobuf==6.32.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - referencing==0.36.2
      - rpds-py==0.27.0
      - rsa==4.9.1
      - six==1.17.0
